Add `project-deref-patterns` under automation
rust-lang/team pull request #1402
Opened 2024-03-16 19:13 UTC by Kobzol

Repo: https://github.com/rust-lang/project-deref-patterns

Based on a discussion [here](https://github.com/rust-lang/team/pull/1388#issuecomment-2002085244).

Extracted from GH:
```toml
org = "rust-lang"
name = "project-deref-patterns"
description = ""
bots = []

[access.teams]
security = "pull"

[access.individuals]
chorman0773 = "admin"
jdno = "admin"
rust-lang-owner = "admin"
pietroalbini = "admin"
Mark-Simulacrum = "admin"
rylev = "admin"
badboy = "admin"
nrc = "admin"
```

2024-03-18 11:24 UTC, rylev requested changes

2024-03-18 12:21 UTC, Nadrieril commented on repos/rust-lang/project-deref-patterns.toml
> +[access.teams]
I'll ask for a new T-lang liaison on Wed (the current one retired), maybe we can wait for that and give repo rights to the liaison when one shows up?

2024-04-05 11:36 UTC, Nadrieril commented
Oops I had forgotten about this! @traviscross is our liaison for the project, work is happening

2024-04-05 13:21 UTC, rylev approved these changes

2024-04-05 13:21 UTC, merged