feat: convert rustlings membership to a team
rust-lang/team pull request #1409
Opened 2024-03-18 17:59 UTC by shadows-withal

I want to add a co-maintainer to Rustlings (which will be done in a later step), so I'm converting the single person repo permission into a team permission. This is not a formal team or anything, just a convenience to let multiple people have the same permission, hence why the team itself is very minimal.

2024-03-18 18:00 UTC, shadows-withal commented
Oh, I also changed the permission to `maintain` because I realized that with `write` I can't really do things like re-trigger CI runs, which is annoying.

2024-03-19 09:02 UTC, rylev requested changes
This looks good if you make the team a marker team. Marker teams are used to indicate "just a collection of people" rather than an actual team in the governance sense.

2024-03-19 09:02 UTC, rylev commented on teams/rustlings.toml
> +kind = "team"
```suggestion
kind = "marker-team"
```

2024-03-19 12:28 UTC, rylev approved these changes

2024-03-19 12:28 UTC, merged