Add email to teams API
rust-lang/team pull request #787
Opened 2022-06-27 03:29 UTC by fee1-dead

cc @pietroalbini

This is for unblocking https://github.com/rust-lang/simpleinfra/pull/110.

2022-06-27 03:30 UTC, fee1-dead commented
oh it doesn't really unblock that PR, I will add something like people.json

2022-09-04 13:14 UTC, pietroalbini commented
Changes look good to me, but GitHub is reporting merge conflicts.

2022-09-04 13:21 UTC, fee1-dead commented
ok github is not good for resolving merge conflicts. Will resolve it in a moment

2022-09-04 13:36 UTC, pietroalbini approved these changes

2022-09-04 13:37 UTC, pietroalbini commented
Code changes still look good! Can someone from core merge this?

2022-09-04 13:46 UTC, Mark-Simulacrum requested changes

2022-09-04 13:46 UTC, Mark-Simulacrum commented on src/schema.rs
> +impl From<Email<'_>> for Option<String> {
This feels like a pretty unfortunate From impl, can we use a named method here?

2022-09-04 13:50 UTC, Mark-Simulacrum approved these changes

2022-09-04 13:52 UTC, merged