Improve getting started advice in README
rust-lang/team pull request #872
Opened 2022-10-21 14:20 UTC by alice-i-cecile

I just went through this process myself, and figured I should leave some basic suggestions to improve the clarity of the relevant parts of the process.

2022-10-21 14:32 UTC, rylev requested changes
Thanks!

2022-10-21 14:32 UTC, rylev commented on README.md
> +You can also add additional information, such as someone's DIscord or Zulip ID by adding additional fields to their `.toml` file.
```suggestion
You can also add additional information, such as someone's Discord or Zulip ID by adding additional fields to their `.toml` file.
```

2022-10-21 15:47 UTC, alice-i-cecile commented on README.md
> +Note that, if you're using this for the first time, some of these checks will fail due to missing API tokens.
Some of the checks are skipped, producing warnings and the tool otherwise works. Let me amend the wording.

2022-10-21 15:47 UTC, alice-i-cecile commented on README.md
> +Note that, if you're using this for the first time, some of these checks will fail due to missing API tokens.
```suggestion
Note that, if you're using this for the first time, some of these checks will be skipped due to missing API tokens.
```

2022-10-24 11:22 UTC, rylev commented on README.md
> +Note that, if you're using this for the first time, some of these checks will be skipped due to missing API tokens.
I'm not sure it makes sense to qualify this with "first time". After all, if they run again (or a hundred more times), the tool will still skip some checks. 

```suggestion
Note that some of these checks will be skipped due to missing API tokens.
```

2022-10-24 15:05 UTC, rylev approved these changes
Thanks for this!! 🎉

2022-10-24 15:05 UTC, merged