Let t-miri use perf and crater
rust-lang/team pull request #898
Opened 2022-12-01 20:24 UTC by saethlin

@jyn514 keeps telling me to submit this
cc @RalfJung @oli-obk 

The Miri team primarily works on a separate repo, but parts of the interpreter live in rust-lang/rust. So it seems like anyone on the team has reason to do perf and crater runs, and should be trusted to do so responsibly. Of course, this change only affects me currently.

2022-12-01 21:04 UTC, jyn514 submitted a review, later dismissed

2022-12-01 21:16 UTC, RalfJung commented
No objection, though I don't think we ever needed crater runs for Miri.

2022-12-02 09:44 UTC, rylev requested changes

2022-12-02 09:44 UTC, rylev commented on teams/miri.toml
> +crater = true
If crater runs have never been needed for miri, and they're relatively rare as is, I think it makes sense to remove this for now.

2022-12-02 16:24 UTC, rylev approved these changes

2022-12-02 16:25 UTC, merged