add psibi to emacs
rust-lang/team pull request #905
Opened 2022-12-23 17:37 UTC by brotzeit

2022-12-29 08:51 UTC, rylev requested changes
@brotzeit I believe you may have forgotten to add them to the team. You've only added their personal information.

2022-12-29 08:57 UTC, brotzeit commented
Sorry, updated.

2022-12-30 18:42 UTC, khionu commented
Can we add a trailing comma to the list?

2023-01-02 10:09 UTC, rylev approved these changes

2023-01-02 10:09 UTC, merged